# Generated by Django 4.0.4 on 2022-04-20 05:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Disciplina')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Adicionada em')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text='Conteúdo abordado pela questão', max_length=256, null=True, verbose_name='Conteúdo')),
                ('grade', models.IntegerField(help_text='Série para qual foi elaborada a questão', null=True, verbose_name='Série')),
                ('statement', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Enunciado')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publicado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
    ]
