# Generated by Django 4.0.4 on 2022-04-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='added_at',
        ),
        migrations.AddField(
            model_name='questao',
            name='tags',
            field=models.ManyToManyField(related_name='Disciplina', to='core.disciplina'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Adicionada em'),
        ),
    ]
