# Generated by Django 4.0.4 on 2022-04-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_disciplina_added_at_questao_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='tags',
            new_name='disciplines',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='discipline',
        ),
    ]
